### ISSUE TITLE
Not able to get access to MCP servers that have been granted access to groups that user belongs to after upgrading from 0.13.0.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#5059]
**Describe the bug**
Not able to get access to MCP servers that have been granted access to groups that user belongs to after upgrading from 0.13.0.

**Pre Req** - Have Entra set up with few users and groups set. Have app registration configured with api permission from obot docs relating to `v0.13.0`.
Have `User1` be part of `Group1`

**Steps to reproduce the problem:**

1. Fresh install of v0.13.0
2. Enable Microsoft Entra provider.
3. Log in as admin user , deleted the existing default ACR that provides access to all MCP servers to all users in global registry.
4. Create ACR1 , that will allow `Group1` to some MCP servers say MCP1 and MCP2
5. Create ACR2 , that will allow `User1` to MCP3
6. Log in as `User1`.
User is able to see and connect (and chat) with MCP1 and MCP2 (from `Group1`) and MCP3. He does not have access to any other MCP server as expected.

7. Upgrade Obot server to latest build from main
As `User1` , I was still connected to  MCP1, MCP2 and MCP3 and was able to chat with all the connected MCP servers as expected.

8. Make necessary changes to the existing Entra app to get it configured to the latest requirements  as described in obot docs relating to `Next` release. I deleted the existing permission that was not needed for the next release (GroupMember.Read.All delegated permission)  and then added  the 2 new application permissions that was needed.

<img width="863" height="311" alt="Image" src="https://github.com/user-attachments/assets/26626145-c5f5-47a3-bcb1-00af3981e386" />

9. Log in a `User1`

Notice that we dont have access to MCP1 and MCP2 servers. The connected MCP server instances get deleted and also these MCP servers are not available in the `Available Connectors` list.
User still has access to MCP3 that was from ACR that provided access to the user directly.

10. Add new ACR that grants access to any mcp server say MCP4 from `Group1`

Notice that `User1` does not get access to MCP4 as well

**Note**

`group_memberships` table does not have group information for `User1`

User-id 4 and 5  that have group info are users that I have not logged in after upgrade.
```
 select * from group_memberships;
 user_id |                  group_id                  |          created_at           
---------+--------------------------------------------+-------------------------------
       4 | entra/ae868713-8b9b-4fd5-9bf3-ef3a0134fe31 | 2025-11-17 21:10:27.876715+00
       4 | entra/7d105e20-ca9d-4a95-8e2c-2b165a790ef8 | 2025-11-17 21:10:27.876715+00
       4 | entra/eadf603c-e737-4ccd-9467-a541e2ee621e | 2025-11-17 21:10:27.876715+00
       4 | entra/0415c556-4da2-48dd-82b6-58423d5d4c8f | 2025-11-17 21:10:27.876715+00
       5 | entra/0415c556-4da2-48dd-82b6-58423d5d4c8f | 2025-11-17 21:14:11.171269+00
(5 rows)

```

As soon as I log in as these users, I see the group info getting deleted from this table.

**Comment by g-linville** [comment]
The core problem here is that, in Sangeetha's setup, Obot was unable to fetch groups for an individual user. I am not sure why this was happening, but I am going to try to reproduce it.

**Comment by sangee2004** [comment]
I had not restarted obot after changing the permission on the Entra side.

Once I restarted obot , I get access to all MCP connectors (access thru group ) now as expected. I had to wait for sometime (up to 10 minutes) for group fetch to be triggered and getting group access.

@g-linville I will keep this issue open  to release note the following:

1. Ideally api permission to the existing entra app should be done before upgrade of obot server to `0.14.0` version is attempted.
2. If obot server was upgraded to  `0.14.0` version  without  making the required api permission changes for the existing entra app , existing connected MCP servers would get deleted and access to groups will stop working.
Admin needs to make required api permission changes for the existing entra app and restart obot server for the changes to be picked up by auth provider.  It could take up to 10 minutes for group access to be restored for the users.

**Comment by g-linville** [comment]
Yeah if the new permissions are added ahead of time, then it won't be an issue. We'll just make note of that in the release notes. @sangee2004

**Comment by g-linville** [comment]
I'm going to move this issue to Testing, now that I have merged a change that will return a 500 error and prevent authentication from continuing if the auth provider fails to fetch groups for a user.

**Comment by g-linville** [comment]
To test this change, all you need to do is misconfigure your auth provider in some way (i.e., insufficient permissions granted to it), and then attempt to log in.

**Comment by sangee2004** [comment]
@g-linville I am trying to test this fix with upgrade from 0.13.0 since users would end up in the state of having a misconfigured Entra provider as soon as they upgrade to latest `main`.

I am not seeing the user being logged out after upgrading to latest `main`. I have waited more than 10 minutes after the upgrade now and still continue to be logged in ( I am using the obot UI )  . I have also not lost any access to the connected MCP server instances and still see the groups assigned to the user. Should we expect the user to be logged out since a group call should have happened and this should have resulted in invalidating the current session and user being logged out ?


Steps that were followed:
1. Install 0.13.0 and have Entra auth provider configured with following permissions

<img width="903" height="238" alt="Image" src="https://github.com/user-attachments/assets/fefcf0ef-805a-4e23-a14e-c59fa8637a07" />

2. Log in as admin user , deleted the existing default ACR that provides access to all MCP servers to all users in global registry.

3. Create ACR1 , that will allow Group1 to some MCP servers say MCP1 and MCP2

4. Create ACR2 , that will allow User1 to MCP3

5. Log in as User1.
User is able to see and connect (and chat) with MCP1 and MCP2 (from Group1) and MCP3. He does not have access to any other MCP server as expected.

6. Upgrade Obot server to latest build from main

As User1 , I was still connected to MCP1, MCP2 and MCP3 and was able to chat with all the connected MCP servers as expected.

I waited for more than 20 minutes now , and I am still continue to be logged in as user1 .
Should we expect the user to be logged out since a group call should have happened and this should have resulted in invalidating the current session and user being logged out ?

**Comment by g-linville** [comment]
@sangee2004 Can you try this again with a brand new Entra app that you have never used before? I think if you add the new permissions, and then remove them, they still end up being usable anyway. I'm not 100% sure about that. But I know I tested this with a brand new app just to be safe and start with a clean slate.

**Comment by sangee2004** [comment]
Will retry from a brand new app registration for 0.13.0 setup.

I do see the removed permissions listed as not being configured for the app , but may continue to be made available to obot app as you suggested.

<img width="911" height="510" alt="Image" src="https://github.com/user-attachments/assets/60e86d55-f812-4aa3-8015-8604146e68b5" />

**Comment by sangee2004** [comment]
When testing with new new app registration for 0.13.0 setup , I am seeing the user log in being blocked as expected after upgrading to latest `main`

User is presented with the following error message:

<img width="1397" height="115" alt="Image" src="https://github.com/user-attachments/assets/f79037d4-7d60-41b4-a282-26af7ed31198" />

Once all the necessary api permissions are fixed for Entra app resgistration , user login will still continue to fail with the same error as above.

Once obot server is restarted , then user is able to log in as expected. 
Users continue to have access to the connected MCP server instances as expected.
